sudo: required

services:
  - docker

env:
  COMPOSE_VERSION: 1.2.0

before_install:
 - curl -L https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose-bin
 - chmod +x docker-compose-bin
 - sudo mv docker-compose-bin /usr/local/bin/docker-compose
 - sudo service docker restart ; sleep 10

script:
  - docker-compose -f docker-compose/test-travis.yml run kuzzle

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/8e145155fbaaf37cffea
    on_success: change
    on_failure: always
    on_start: never
  email: false