kuzzle:
  image: kuzzleio/kuzzle
  command: /run-debug.sh
  volumes:
    - "../features/fixtures.json:/fixtures.json"
  ports:
    - "7512:7512"
    - "7511:7511"
    - "8080:8080"
    - "8081:8081"
  links:
    - elasticsearch
    - redis
  environment:
    - LIKE_A_VIRGIN
    - FIXTURES=/fixtures.json
    - DEFAULT_MAPPING
    - FEATURE_COVERAGE

kuzzleBo:
  image: kuzzleio/bo-dev:alpine
  volumes:
    - "..:/var/app"
  ports:
    - "3000:3000"
    - "8082:8080"
    - "9876:9876"
    - "35729:35729"
  links:
    - kuzzle
  environment:
    - DEVELOPMENT
    - KUZZLE_URL

redis:
  image: redis:3.0-alpine

elasticsearch:
  image: kuzzleio/elasticsearch:2.2
