kuzzle:
  image: kuzzleio/kuzzle:0.9.6
  command: /run-debug.sh
  ports:
    - "7512:7512"
    - "7511:7511"
    - "8080:8080"
    - "8081:8081"
  links:
    - elasticsearch
    - redis
  environment:
    - LIKE_A_VIRGIN
    - FIXTURES
    - DEFAULT_MAPPING
    - FEATURE_COVERAGE

kuzzleBo:
  image: kuzzleio/bo
  volumes:
    - "..:/var/app"
  ports:
    - "3000:3000"
    - "8082:8080"
    - "9876:9876"
    - "35729:35729"
  links:
    - kuzzle
  environment:
    - DEVELOPMENT

redis:
  image: redis:3.0.2

elasticsearch:
  image: elasticsearch:1.5.2
