loadbalancer:
  image: kuzzleio/proxy:alpine
  ports:
    - "7511:7511"
    - "7512:7512"
    - "8083:8080"

kuzzleBo:
  image: kuzzleio/bo-dev:alpine
  command: /run-dev.sh
  volumes:
    - "..:/var/app"
  ports:
    - "3000:3000"
    - "8082:8080"
    - "9876:9876"
    - "35729:35729"
  links:
    - loadbalancer:kuzzle
  environment:
    - DEVELOPMENT
    - KUZZLE_URL

kuzzle:
  image: kuzzleio/kuzzle:develop
  command: /run-debug.sh
  volumes:
    - "../features/fixtures.json:/fixtures.json"
  ports:
    - "8080:8080"
    - "8081:8081"
  links:
    - rabbit
    - elasticsearch
    - redis
    - loadbalancer
  environment:
    - MQ_BROKER_ENABLED=1
    - FEATURE_COVERAGE
    - kuzzle_fixtures=/fixtures.json

rabbit:
  image: kuzzleio/rabbitmq:alpine
  ports:
    - "61613:61613"
    - "1883:1883"
    - "5672:5672"
    - "15672:15672"

redis:
  image: redis:3.0-alpine

elasticsearch:
  image: kuzzleio/elasticsearch:2.2
