kuzzle:
  image: kuzzleio/kuzzle:1.0.0-beta.1
  volumes:
    - "../features/fixtures.json:/fixtures.json"
  ports:
    - "7512:7512"
    - "7511:7511"
    - "8080:8080"
    - "8081:8081"
  links:
    - elasticsearch
    - redis
  environment:
    - LIKE_A_VIRGIN=1
    - FIXTURES=/fixtures.json
    - DEFAULT_MAPPING
    - FEATURE_COVERAGE

kuzzleBo:
  image: kuzzleio/bo-test
  command: /run-test.sh
  volumes:
    - "..:/var/app"
    - "../features/kuzzle-config.js:/var/app/public/javascripts/config.js"
  ports:
    - "3000:3000"
    - "8082:8080"
    - "9876:9876"
  links:
    - kuzzle
  environment:
      - DEBUG_PHANTOM

redis:
  image: redis:3.0

elasticsearch:
  image: elasticsearch:1.7
