proxy:
  image: kuzzleio/proxy:alpine
  ports:
    - "7511:7511"
    - "7512:7512"

bo:
  image: kuzzleio/bo-test:alpine
  command: /run-test.sh
  volumes:
    - "..:/var/app"
    - "../features/kuzzle-config.js:/var/app/src/javascripts/config.js"
  ports:
    - "3000:3000"
  links:
    - proxy:kuzzle
    # add link to elasticsearch in order to perform a dump
    - elasticsearch
  environment:
    - DEBUG_PHANTOM
    - KUZZLE_URL

kuzzle:
  image: kuzzleio/kuzzle:develop
  volumes:
    - "../features/fixtures.json:/fixtures.json"
  links:
    - elasticsearch
    - redis
    - proxy:api
  environment:
    - FIXTURES=/fixtures.json
    - FEATURE_COVERAGE

redis:
  image: redis:3.0-alpine

elasticsearch:
  image: kuzzleio/elasticsearch:2.2
